### PR TITLE
Codestyle

### PR DESCRIPTION
**Pull request by 810**

### CODE REVIEW

**Comment by astridx** [comment]
I agree with the code styles and the slash for windows. Thanks :)

**Comment by yvesh** [comment]
any reason we are not following the Joomla code style?! (3 - 2 - 2 spaces for methods)

https://developer.joomla.org/coding-standards/docblocks.html

**Comment by puneet0191** [comment]
I am not really sure about the code-style changes here, I think it was 3, 2, 2 spaces isn't it?

**Comment by 810** [comment]
I use the new codestyle (master branch) https://github.com/joomla/coding-standards
And when i click phpstorm (code- reformat code) then its always fixed to 3-1-1
i don't why

**Comment by yvesh** [comment]
@810 because PhpStorm can't do doc comments in joomla style.. It's a known issue for a long time :(

Even in the new coding standards (which are just a port to phpcs 2.8 + new php constructs) we still have the same doc comment indentation.

@mbabker or did that change recently? (still 3-2-2 spaces for methods etc. like in the manual on developer)

**Comment by mbabker** [comment]
Standard hasn't changed.  PhpStorm doesn't handle our spacing rules well so you can't rely on it to auto-format.

**Comment by roland-d** [comment]
I have reported this to the developer of PhpStorm, he is going to take a look at it.

**Pull request merged**
